### ISSUE TITLE
Scaling a service

### ISSUE THREAD

**Issue by cbiale** [avkonst/overnode#68]
Is it possible to scale a service?
If possible, what is the command?

**Comment by avkonst** [comment]
You need to change overnode.yml config by defining where (what nodes/hosts) a container should be placed. Once the config is updated run `overnode up` command to apply the change.

**Comment by cbiale** [comment]
```
id: <project-id>
version: <compose-file-version>


# zero, one or many stack sections
<stack-name>:
    # zero, one or many references to compose files
    <compose-file-reference.yml>: <placement-rule>
```
would it change `<placement-rule>`?

From what I understand, that is going to depend on the number of actual hosts. That is, if I have only one host, I will have only one instance of the container.

For example, if I want to build a cluster of a database with three instances, should I have 3 hosts?

**Comment by jtagcat** [comment]
Yes. Software can't pull out servers out of a magic hat (yes VMs, but out of scope).

If `<placement-rule>` is `*` it will be on all available hosts.

> For example, if I want to build a cluster of a database with three instances, should I have 3 hosts?

Overnode is meant to be multi-machine docker-compose — in essence, yes. (If you really want the same DB on the same machine, you may work with slightly different duplicates in docker-compose.)

**Comment by cbiale** [comment]
Great, thanks for the explanation!!
I'm  going to close this issue.
