### ISSUE TITLE
Removing a node from an `overnode.yml` definition doesn't stop the service on `overnode up`.

### ISSUE THREAD

**Issue by jtagcat** [avkonst/overnode#71]
#### Initial:
```
nginx:
    nginx.yml: 1,2-3,4
```
State: running on 1,2,3,4
#### Changed:
```
nginx:
    nginx.yml: 1,2-3
```
State: running on 1,2,3,**4**  
Expected state: running on 1,2,3

**Comment by avkonst** [comment]
This is the same as docker compose works. Ot does not remove items without 'remove orphans' flag.

**Comment by jtagcat** [comment]
Forwarded an user report here to come and fix it today.
rtfm :^)
Pardon
